spring:
  datasource:
    url : jdbc:mysql://localhost:3307/todolist?createDatabaseIfNotExist=true
    password: yasas
    username: root
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8081